<main>
    <h1>Votre profil :</h1>
    <section>
        <h2 class="sr-only">Vos infos</h2>
        <p>
            Votre pseudo : 
        </p>
        <p>
            Votre adresse mail :
        </p>
    </section>
    <section>
        <h2 class="sr-only">Vos infos</h2>
        <?php foreach($data as $user){ ?>
        <p>
            <?= $user->getUser(); ?>
        </p>
        <p>
            <?= $user->getEmail(); ?>
        </p>
        <?= } ?>
    </section>
    <section>
        <h2>Modifier votre mot de passe :</h2>
        <form>
            <fieldset>
                <label for="oldPassword">Votre mot de passe actuel :</label>
                <input type="password" name="oldPassword"/>
            </fieldset>
            <fieldset>
                <label for="newPassword">Votre nouveau mot de passe :</label>
                <input type="password" name="newPassword"/>
            </fieldset>
            <input type="submit" name="submit" value="Changer de mot de passe"/>
        </form>
    </section>
</main>