<section class="container py-5">
        <h1>Les utilisateurs :</h1>
        <table class="table">
                <thead>
                    <tr>
                        <th>
                            #
                        </th>
                        <th>
                            Nom d'utilisateur
                        </th>
                        <th>
                            Email
                        </th>
                        <th>
                            Role
                        </th>
                        <th>
                            Actions
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                    foreach($data as $user){ 
                    ?>
                    <tr>
                        <td><?= $user->getId(); ?></td>
                        <td><?= $user->getUser(); ?></td>
                        <td><?= $user->getEmail(); ?></td>
                        <td><?= $user->getRole(); ?></td>
                        <td>
                            <a class="btn btn-info" href="/res03-projet-final/admin/user/<?= $user->getId(); ?>/edit" role="button">Editer</a>
                            <a class="btn btn-danger" href="/res03-projet-final/admin/user/<?= $user->getId(); ?>/delete" role="button">Supprimer</a>
                        </td>
                    </tr>
                    <?php }?>
                </tbody>
            </table>
    </section>
