<main id="home">
    <h1 class="sr-only">
        Portfolio d'Azurior
    </h1>
    <figure>
        <img src="assets/img/title.png" alt="Titre du site qui est Portfolio d'Azurior"></img>
    </figure>
    <section id="carousel">
        <h2 class="sr-only">carousel</h2>
        <section class="wrapper">
            <h3 class="sr-only">wrapper</h3>
            <section class="container">
                <h4 class="sr-only">Container</h4>
                <section class="slider">
                    <h5 class="sr-only">Image Carousel</h5>
                </section>
            </section>
            <section class="dot"><h4 class="sr-only">Dot</h4></section>
            <button class="navigator navigator1" id="0">
                <i class="fa fa-angle-left"></i>
            </button>
            <button class="navigator navigator2" id="1">
                <i class="fa fa-angle-right"></i>
            </button>
        </section>
    </section>
    <section id="About">
        <h2>A propos de moi</h2>
        <p>
            Après une formation de Développeur Web et Web mobile au sein de la 3w Academy, j'ai eu pour projet final de faire un site internet. Ce dernier est un portfolio de ce que je sais faire sur photoshop.
        </p>
        <p>
            J'adore tout ce qui est créatif. Que ce soit la musique, ou le dessin. C'est pour cela que ça fait 10 ans que j'utilise Photoshop. Grâce à cela, je peux vous montrez ce que je sais faire, mais aussi, peut-être, vous faire des images 100% personnalisé
        </p>
    </section>
    <section id="styles">
        <h2 class="sr-only">Les styles</h2>
    </section>
</main>
<script src="../res03-projet-final/assets/js/index.js"></script>