<main id="home">
    <h1>
        Portfolio d'Azurior
    </h1>
    <section id="carousel">
        <section class="wrapper">
            <h2 class="sr-only">Carousel</h2>
            <section class="container">
                <section class="slider">
                    <h3 class="sr-only">Image Carousel</h3>
                </section>
            </section>
            <section class="dot"><h3 class="sr-only">Dot</h3></section>
            <button class="navigator navigator1" id="0">
                <i class="fa fa-angle-left"></i>
            </button>
            <button class="navigator navigator2" id="1">
                <i class="fa fa-angle-right"></i>
            </button>
        </section>
    </section>
    <section id="About">
        <h2>A propos de moi</h2>
        <p>Actuellement en formation Développeur Web et Web mobile à la 3w Academy, j'ai pour projet final de faire un site internet.</p>
        <p>Ce site internet va regrouper un portfolio des images déjà faites (que ce soit des wallpapers, des logos, ou encore des scenes twitch), avec la possibilité pour vous,
        de me demandez si je peux vous faire quelque chose de personnalisé</p>
        <p>Je touche à photoshop depuis environ 10 ans. Ceci reste un hobby, et je ne suis en rien un Designer pro</p>
        <p>J'espère que vous en aurez pour vos yeux et je ne peux que vous souhaiter de profiter un maximum !</p>
    </section>
    <section id="styles">
        <h2 class="sr-only">Les styles</h2>
    </section>
</main>
<script src="../res03-projet-final/assets/js/index.js"></script>