<main id="authentification">
<h1>Page de connexion et d'inscription</h1>
<section>
    <h2 class="sr-only">Authentification</h2>
    <section id="loginForm">
    <h3>Connexion</h3>
    <form action="/res03-projet-final/check-login" method="POST">
        <input type="hidden" name="formLogin" id="formLogin" value="formLogin" /> 
        <fieldset>
            <label for="loginEmail">Email :</label>
            <input type="email" name="loginEmail" id="loginEmail"/>
            <?php if(isset($_SESSION['formErrorMail'])){ ?>
            <p><?= $_SESSION['formErrorMail']?></p>
            <?php } ?>
        </fieldset>
        <fieldset>
            <label for="loginPassword">Mot de passe :</label>
            <input type="password" name="loginPassword" id="loginPassword"/>
            <?php if(isset($_SESSION['formErrorPassword'])){ ?>
            <p><?= $_SESSION['formErrorPassword']?></p>
            <?php } ?>
        </fieldset>
        <input type="submit" name="submit" value="Connexion"/>
    </form>
</section>
<section id="registerForm">
    <h3>S'inscrire</h3>
    <form action="/res03-projet-final/check-register" method="POST" id="formRegister">
        <input type="hidden" name="formRegister" value="formRegister" /> 
        <fieldset>
            <label for="register-username">Pseudo :</label>
            <input type="text" id="register-username" name="register-username"/>
        </fieldset>
        <fieldset>
            <label for="register-email">Email :</label>
            <input type="email" id="register-email" name="register-email"/>
        </fieldset>
        <fieldset>
            <label for="register-password">Votre mot de passe :</label>
            <input type="password" id="register-password" name="register-password"/>
            <?php if(isset($_SESSION['errorPassword'])){ ?>
                <p><?= $_SESSION['errorPassword']?></p>
            <?php } ?>
        </fieldset>
        <fieldset>
            <label for="register-confPassword">Confirmation du mot de passe :</label>
            <input type="password" id="register-confPassword" name="register-confPassword"/>
        </fieldset>
        <?php if(isset($_SESSION['errorPasswordAndConf'])){ ?>
            <p><?= $_SESSION['errorPasswordAndConf']?></p>
        <?php } ?>
        <input type="submit" name="submit" value="S'inscrire"/>
    </form>
</section>
</section>
</main>
<script type="module" src="../res03-projet-final/assets/js/validate-user.js"></script>