<footer>
    <section>
        <h2 class="sr-only">Footer</h2>
        <ul>
            <li>
                <a target="_blank" href="https://www.linkedin.com/in/tony-gohin/"><i class="bi bi-linkedin"></i></a>
            </li>
            <li>
                <a target="_blank" href="https://github.com/Azurior"><i class="bi bi-github"></i></a>
            </li>
            <li>
                <a target="_blank" href="https://discord.gg/DFcRCQymwF"><i class="bi bi-discord"></i></a>
            </li>
        </ul>
 
        <p>© Copyright Azurior</p>
    </section>
</footer>