<header class="header">
    <input type="checkbox" class="side-menu" id="side-menu"/>
    <label class="hamb" for="side-menu"><span class="hamb-line"></span></label>
    <nav class="nav">
        <ul class="menu">
            <li><a href="/res03-projet-final/home">Accueil</a></li>
            <li><a href="/res03-projet-final/projects">Mes Projets</a></li>
            <li><a href="/res03-projet-final/devis">Devis</a></li>
        </ul>
        <p>
            <?php if(isset($_SESSION['role']) && $_SESSION['role'] === 'user'){ ?>
                    
                        <a href="/res03-projet-final/user/<?= $_SESSION['id'] ?>" id="user"><?= $_SESSION['user'] ?></a>
        </p>
        <p>
                    /
        </p>
        <p>
                    <a href="/res03-projet-final/logout" id="logout">
                        Deconnexion
                    </a>
        </p>
                <?php }else if(isset($_SESSION['role']) && $_SESSION['role'] === 'admin'){ ?>
        <p>          
                        <a href="/res03-projet-final/user/<?= $_SESSION['id'] ?>" id="user"><?= $_SESSION['user'] ?></a>
        </p>
        <p>
                    |
        </p>
        <p>
                    <a href="/res03-projet-final/admin" id="admin">
                        Admin
                    </a>
        </p>
        <p>
                     · 
        </p>
        <p>
                    <a href="/res03-projet-final/logout" id="logout">
                        Deconnexion
                    </a>
        </p>
        <p>
                <?php }else if(!isset($_SESSION['role'])){ ?>
                    <a href="/res03-projet-final/authentificator">
                        Connexion / S'inscrire
                    </a>
                <?php }?>
        </p>
    </nav>
</header>