<header class="header">
    <input type="checkbox" class="side-menu" id="side-menu"/>
    <label class="hamb" for="side-menu"><span class="hamb-line"></span></label>
    <nav class="nav">
        <ul class="menu">
            <li><a href="/res03-projet-final/home">Accueil</a></li>
            <li><a href="/res03-projet-final/projects">Mes Projets</a></li>
            <li><a href="/res03-projet-final/devis">Devis</a></li>
        </ul>
        <p>
            <?php if(isset($_SESSION['role']) && $_SESSION['role'] === 'user'){ ?>
                    
                        <?= $_SESSION['user'] ?>
                    
                    /
                    <a href="/res03-projet-final/logout" id="logout">
                        Deconnexion
                    </a>
                <?php }else if(isset($_SESSION['role']) && $_SESSION['role'] === 'admin'){ ?>
                    
                        <?= $_SESSION['user'] ?>
                    
                    | 
                    <a href="/res03-projet-final/admin">
                        Admin
                    </a>
                     · 
                    <a href="/res03-projet-final/logout" id="logout">
                        Deconnexion
                    </a>
                <?php }else if(!isset($_SESSION['role'])){ ?>
                    <a href="/res03-projet-final/authentificator">
                        Connexion / S'inscrire
                    </a>
                <?php }?>
        </p>
    </nav>
</header>