<main id="devis">
    <h1>Demande de devis</h1>
    <p>Vous ne pouvez remplir qu'un seul formulaire à la fois</p>
    <p>Sachez qu'il vous faut être <strong><a href="/res03-projet-final/authentificator">connecté</a></strong> pour pouvoir envoyer une demande de devis !</p>
    <section>
        <h2 class="sr-only">Les différents devis</h2>
        <section id="devisWallpaper">
            <h3>Demande de devis pour un fond d'écran :</h3>
            <form action="/res03-projet-final/check-wallpaper" method="POST">
                <input type="hidden" name="formWallpaper" id="formWallpaper" value="formWallpaper" />
                <fieldset>
                    <label for="themeWallpaper">Le thème de votre fond d'écran :</label>
                    <input type="text" name="themeWallpaper" id="themeWallpaper"/>
                </fieldset>
                <p>Pour la partie qui suit, vous allez devoir choisir votre couleur princiipale et secondaire (et les optionnelles). Je vous conseille ce : <a target="_blank" href="https://htmlcolorcodes.com/fr/selecteur-de-couleur/">site</a></p> 
                <p>Choisissez vos couleurs, et remplissez le champ de chaque couleur que vous voulez (en valeur hexadécimale, donc avec le " # ")</p>
                <fieldset>
                    <label for="primaryColorWallpaper">Votre couleur principale :</label>
                    <input type="text" name="primaryColorWallpaper" id="primaryColorWallpaper"/>
                </fieldset>
                <fieldset>
                    <label for="secondaryColorWallpaper">Votre couleur secondaire :</label>
                    <input type="text" name="secondaryColorWallpaper" id="secondaryColorWallpaper"/>
                </fieldset>
                <fieldset>
                    <label for="option1ColorWallpaper">Ajouter une couleur optionnelle :</label>
                    <input type="text" name="option1ColorWallpaper" id="option1ColorWallpaper"/>
                </fieldset>
                <fieldset>
                    <label for="option2ColorWallpaper">Ajouter une couleur optionnelle :</label>
                    <input type="text" name="option2ColorWallpaper" id="option2ColorWallpaper"/>
                </fieldset>
                <fieldset>
                    <label for="option3ColorWallpaper">Ajouter une couleur optionnelle :</label>
                    <input type="text" name="option3ColorWallpaper" id="option3ColorWallpaper"/>
                </fieldset>
                <fieldset>
                    <label for="textWallpaper">Votre texte / Pseudo / Autre :</label>
                    <input type="text" name="textWallpaper" id="textWallpaper"/>
                </fieldset>
                <fieldset>
                    <label for="sizeProjectWallpaper">La taille de votre image :</label>
                    <input type="text" name="sizeProjectWallpaper" id="sizeProjectWallpaper"/>
                </fieldset>
                <?php if(isset($_SESSION['role']) && ($_SESSION['role'] === 'user' || $_SESSION['role'] === 'admin')){ ?>
                    <input type="submit" name="submit" value="Envoyer"/>
                <?php } ?>
            </form>
        </section>
        <section id="devisLogo">
            <h3>Demande de devis pour un logo :</h3>
            <form action="/res03-projet-final/check-logo" method="POST">
                <input type="hidden" name="formLogo" id="formLogo" value="formLogo" />
                <fieldset>
                    <label for="themeLogo">Le thème de votre logo :</label>
                    <input type="text" name="themeLogo" id="themeLogo"/>
                </fieldset>
                <p>Pour la partie qui suit, vous allez devoir choisir votre couleur principale et secondaire (et les optionnelles). Je vous conseille ce : <a target="_blank" href="https://htmlcolorcodes.com/fr/selecteur-de-couleur/">site</a></p> 
                <p>Choisissez vos couleurs, et remplissez le champ de chaque couleur que vous voulez (en valeur hexadécimale, donc avec le " # ")</p>
                <fieldset>
                    <label for="primaryColorLogo">Votre couleur principale :</label>
                    <input type="text" name="primaryColorLogo" id="primaryColorLogo"/>
                </fieldset>
                <fieldset>
                    <label for="secondaryColorLogo">Votre couleur secondaire :</label>
                    <input type="text" name="secondaryColorLogo" id="secondaryColorLogo"/>
                </fieldset>
                <fieldset>
                    <label for="option1ColorLogo">Ajouter une couleur optionnelle :</label>
                    <input type="text" name="option1ColorLogo" id="option1ColorLogo"/>
                </fieldset>
                <fieldset>
                    <label for="option2ColorLogo">Ajouter une couleur optionnelle :</label>
                    <input type="text" name="option2ColorLogo" id="option2ColorLogo"/>
                </fieldset>
                <fieldset>
                    <label for="option3ColorLogo">Ajouter une couleur optionnelle :</label>
                    <input type="text" name="option3ColorLogo" id="option3ColorLogo"/>
                </fieldset>
                <fieldset>
                    <label for="textLogo">Votre texte / Pseudo / Autre :</label>
                    <input type="text" name="textLogo" id="textLogo"/>
                </fieldset>
                <fieldset>
                    <label for="sizeProjectLogo">La taille de votre image :</label>
                    <input type="text" name="sizeProjectLogo" id="sizeProjectLogo"/>
                </fieldset>
                <?php if(isset($_SESSION['role']) && ($_SESSION['role'] === 'user' || $_SESSION['role'] === 'admin')){ ?>
                    <input type="submit" name="submit" value="Envoyer"/>
                <?php } ?>
        </form>
        </section>
        <section id="devisScene">
            <h3>Demande de devis pour des scènes twitch :</h3>
            <form action="/res03-projet-final/check-scene" method="POST">
                <input type="hidden" name="formScene" id="formScene" value="formScene" />
                <fieldset>
                    <label for="numberScene">Nombre de scènes que vous voulez : (minimum 1, maximum 15)</label>
                    <input type="number" id="numberScene" name="numberScene" min="1" max="15">
                </fieldset>
                <fieldset>
                    <label for="description">Une description de ce que vous voulez :</label>
                    <textarea id="description" name="description" rows="5" cols="33">Expliquer votre projet en quelques mots, ce que doivent faire les scènes</textarea>
                </fieldset>
                <fieldset>
                    <label for="themeScene">Le thème de vos scènes :</label>
                    <input type="text" name="themeScene" id="themeScene"/>
                </fieldset>
                <p>Pour la partie qui suit, vous allez devoir choisir votre couleur principale et secondaire (et les optionnelles). Je vous conseille ce : <a target="_blank" href="https://htmlcolorcodes.com/fr/selecteur-de-couleur/">site</a></p> 
                <p>Choisissez vos couleurs, et remplissez le champ de chaque couleur que vous voulez (en valeur hexadécimale, donc avec le " # ")</p>
                <fieldset>
                    <label for="primaryColorScene">Votre couleur principale :</label>
                    <input type="text" name="primaryColorScene" id="primaryColorScene"/>
                </fieldset>
                <fieldset>
                    <label for="secondaryColorScene">Votre couleur secondaire :</label>
                    <input type="text" name="secondaryColorScene" id="secondaryColorScene"/>
                </fieldset>
                <fieldset>
                    <label for="option1ColorScene">Ajouter une couleur optionnelle :</label>
                    <input type="text" name="option1ColorScene" id="option1ColorScene"/>
                </fieldset>
                <fieldset>
                    <label for="option2ColorScene">Ajouter une couleur optionnelle :</label>
                    <input type="text" name="option2ColorScene" id="option2ColorScene"/>
                </fieldset>
                <fieldset>
                    <label for="option3ColorScene">Ajouter une couleur optionnelle :</label>
                    <input type="text" name="option3ColorScene" id="option3ColorScene"/>
                </fieldset>
                <fieldset>
                    <label for="textScene">Votre texte / Pseudo / Autre :</label>
                    <input type="text" name="textScene" id="textScene"/>
                </fieldset>
                <fieldset>
                    <label for="sizeProjectScene">La taille de votre image :</label>
                    <input type="text" name="sizeProjectScene" id="sizeProjectScene"/>
                </fieldset>
                <?php if(isset($_SESSION['role']) && ($_SESSION['role'] === 'user' || $_SESSION['role'] === 'admin')){ ?>
                    <input type="submit" name="submit" value="Envoyer"/>
                <?php } ?>
        </form>
        </section>
    </section>
</main>
<script src="../res03-projet-final/assets/js/validFormDevis.js"></script>