<h1>Les Categories :</h1>

<a href='/res03-projet-final/admin/categories/create' type="button" class="btn btn-success">Ajouter une nouvelle catégorie</a>

<table class="table">
                <thead>
                    <tr>
                        <th>
                            #
                        </th>
                        <th>
                            Titre
                        </th>
                        <th>
                            Image
                        </th>
                        <th>
                            Lié à
                        </th>
                        <th>
                            Action
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                    foreach($data as $cat){ 
                    ?>
                    <tr>
                        <td><?= $cat->getId(); ?></td>
                        <td><?= $cat->getTitle(); ?></td>
                        <td><?= $cat->getIdMedia(); ?></td>
                        <td><?= $cat->getIdArticles(); ?></td>
                        <td>
                            <a class="btn btn-primary" href="/res03-projet-final/admin/categories/<?= $cat->getId(); ?>/edit" role="button">Éditer</a>
                            <a class="btn btn-danger" href="/res03-projet-final/admin/categories/<?= $cat->getId(); ?>/delete" role="button">Supprimer</a>
                        </td>
                    </tr>
                    <?php }?>
                </tbody>
            </table>
