<h2>Ajouter une catégorie :</h2>
<form method='post' enctype="multipart/form-data">
    <input type="hidden" name="formName" value="fileUpload" />
    <fieldset>
        <label for="title">Titre de la catégorie :</label>
        <input type="title" name="title"/>
    </fieldset>
    <fieldset>
        <label for="file">Image :</label>
        <input type="file" name="file"/>
    </fieldset>
    <input type="submit" value="Ajouter"/>
</form>