
<h1>Les Projets :</h1>

<a href='/res03-projet-final/admin/projects/create' type="button" class="btn btn-success">Ajouter un nouveau projet</a>
<table class="table">
                <thead>
                    <tr>
                        <th>
                            #
                        </th>
                        <th>
                            Titre du projet
                        </th>
                        <th>
                            Action
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                    foreach($data as $project){ 
                    ?>
                    <tr>
                        <td><?= $project->getId(); ?></td>
                        <td><?= $project->getText(); ?></td>
                        <td>
                            <a class="btn btn-primary" href="/res03-projet-final/admin/projects/<?= $project->getId(); ?>/edit" role="button">Éditer</a>
                            <a class="btn btn-danger" href="/res03-projet-final/admin/projects/<?= $project->getId(); ?>/delete" role="button">Supprimer</a>
                        </td>
                    </tr>
                    <?php }?>
                </tbody>
            </table>
 