<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Admin Utilisateurs</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    </head>
    <body class=container-fluid>
        <main class="container py-5">
            <h1>Les Projets :</h1>

            <a href='projects/create'>Ajouter un nouveau projet</a>
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            #
                        </th>
                        <th>
                            Titre du projet
                        </th>
                        <th>
                            Action
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                    foreach($data as $project){ 
                    ?>
                    <tr>
                        <td><?= $project->getId(); ?></td>
                        <td><?= $project->getText(); ?></td>
                        <td>Action</td>
                    </tr>
                    <?php }?>
                </tbody>
            </table>
        </main>
    </body>
</html>