<!DOCTYPE html>
<html lang="fr" prefix="og: https://ogp.me/ns#">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>Portfolio Azurior</title>
      <link rel="stylesheet" href="assets/style/css/style.css">
    </head>
    <body>
        <?php
        require 'partials/_header.phtml';
        
        var_dump($page);
        
        require $page.'/'.$page.'.phtml';
        
        require 'partials/_footer.phtml'; 
        ?>
    </body>
</html>