<h1>
    <nav>
        <ul>
            <li>
                <a href="admin">Accueil</a>
            </li>
            <li>
                <a href="admin/user">Users</a>
            </li>
            <li>
                <a href="admin/projects">Projets</a>
            </li>
            <li>
                <a href="admin/categories">Categories</a>
            </li>
            <li>
                <a href="admin/articles">Articles</a>
            </li>
        </ul>
    </nav>
</h1>