<h1>
    <nav>
        <ul>
            <li>
                <a href="">Accueil</a>
            </li>
            <li>
                <a href="admin-users">Users</a>
            </li>
            <li>
                <a href="admin-projects">Projets</a>
            </li>
            <li>
                <a href="admin-categories">Categories</a>
            </li>
            <li>
                <a href="admin-articles">Articles</a>
            </li>
        </ul>
    </nav>
</h1>