<h1>
    <nav>
        <ul>
            <li>
                <a href="/res03-projet-final/admin">Accueil</a>
            </li>
            <li>
                <a href="/res03-projet-final/admin/users">Users</a>
            </li>
            <li>
                <a href="/res03-projet-final/admin/projects">Projets</a>
            </li>
            <li>
                <a href="/res03-projet-final/admin/categories">Categories</a>
            </li>
            <li>
                <a href="/res03-projet-final/admin/articles">Articles</a>
            </li>
        </ul>
    </nav>
</h1>