
            <h1>Les Articles :</h1>

            <a href='/res03-projet-final/admin/articles/create'>Ajouter un nouvel article</a>
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            #
                        </th>
                        <th>
                            Titre
                        </th>
                        <th>
                            Texte
                        </th>
                        <th>
                            Image
                        </th>
                        <th>
                            Description
                        </th>
                        <th>
                            Lié à Catégorie 
                        </th>
                        <th>
                            Action
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                    foreach($data as $article){ 
                    ?>
                    <tr>
                        <td><?= $article->getId(); ?></td>
                        <td><?= $article->getTitle(); ?></td>
                        <td><?= $article->getText(); ?></td>
                        <td><?= $article->getText(); ?></td>
                        <td><?= $article->getDescription(); ?></td>
                        <td><?= $article->getIdCategories(); ?></td>
                        <td>Action</td>
                    </tr>
                    <?php }?>
                </tbody>
            </table>
